In [151]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [152]:
df = pd.read_csv("FXtrades.csv")
df

,Trades,Header,DataDiscriminator,Asset Category,Currency,Symbol,Date/Time,Quantity,T. Price,Unnamed: 9,Proceeds,Comm in USD,Unnamed: 12,Unnamed: 13,MTM in USD,Code
0,Trades,Data,Order,Forex,CAD,USD.CAD,"2021-02-18, 16:30:50","-100,000",1.26732,NaN,126732,-2,NaN,NaN,-36.33304,NaN
1,Trades,Data,Order,Forex,CAD,USD.CAD,"2021-02-19, 07:15:45","100,000",1.26289,NaN,-126289,-2,NaN,NaN,-106.76452,NaN
2,Trades,SubTotal,NaN,Forex,CAD,USD.CAD,NaN,0,NaN,NaN,443,-4,NaN,NaN,-143.09756,NaN
3,Trades,Total,NaN,Forex,CAD,NaN,NaN,NaN,NaN,NaN,443,-4,NaN,NaN,-143.09756,
4,Trades,Total,NaN,Forex,USD,NaN,NaN,NaN,NaN,NaN,-143.09756,-4,NaN,NaN,-143.09756,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,Trades,SubTotal,NaN,Bonds,USD,MUR 6 7/8 08/15/24,NaN,0,NaN,NaN,150,-29.75,0,120.25,-49.8001,NaN
60,Trades,Data,Order,Bonds,USD,SIG 4.7 06/15/24 4.5953793%,"2021-03-10, 09:53:11","50,000",100.25,100,-50125,-47.5,50172.5,0,-125,O
61,Trades,Data,Order,Bonds,USD,SIG 4.7 06/15/24 4.57111504%,"2021-04-06, 13:03:22","-50,000",100.375,100.519997,50187.5,-36.5,-50172.5,-21.5,-72.4986,C;P
62,Trades,SubTotal,NaN,Bonds,USD,SIG 4.7 06/15/24,NaN,0,NaN,NaN,62.5,-84,0,-21.5,-197.4986,NaN
63,Trades,Total,NaN,Bonds,USD,NaN,NaN,NaN,NaN,NaN,292223.75,-341,-285528.75,6354,-1319.543,

In [153]:
def preprocessing(data):
    data = data[data.Header == 'Data']
    data.Symbol.loc[data['Asset Category'] == 'Bonds'] = data.Symbol.loc[data['Asset Category'] == 'Bonds'].apply(
        lambda x: ' '.join(x.split(' ')[:-1]))
    data = data[data.Symbol.duplicated(keep=False)]
    data['Quantity'] = data['Quantity'].apply(
        lambda x: x.replace(',', '') if x is not np.nan else x).astype(float)
    data['Proceeds'] = data['Proceeds'].apply(
        lambda x: x.replace(',', '') if x is not np.nan else x).astype(float)
    data['Date/Time'] = data['Date/Time'].astype('datetime64[ns]')
    data = data.sort_values(['Symbol', 'Date/Time'])

    data_currency = data[data['Asset Category'] == 'Forex'].reset_index(drop=True)
    data_bonds = data[data['Asset Category'] == 'Bonds'].reset_index(drop=True)
    return data_currency, data_bonds


data_currency, data_bonds = preprocessing(df)

In [154]:
data_bonds

,Trades,Header,DataDiscriminator,Asset Category,Currency,Symbol,Date/Time,Quantity,T. Price,Unnamed: 9,Proceeds,Comm in USD,Unnamed: 12,Unnamed: 13,MTM in USD,Code
0,Trades,Data,Order,Bonds,USD,MUR 6 7/8 08/15/24,2021-02-04 15:45:37,10000.0,100.5,100.5,-10050.0,-10,10060,0,0,O
1,Trades,Data,Order,Bonds,USD,MUR 6 7/8 08/15/24,2021-03-29 10:17:04,-10000.0,102,102.498001,10200.0,-19.75,-10060,120.25,-49.8001,C
2,Trades,Data,Order,Bonds,USD,SIG 4.7 06/15/24,2021-03-10 09:53:11,50000.0,100.25,100,-50125.0,-47.5,50172.5,0,-125,O
3,Trades,Data,Order,Bonds,USD,SIG 4.7 06/15/24,2021-04-06 13:03:22,-50000.0,100.375,100.519997,50187.5,-36.5,-50172.5,-21.5,-72.4986,C;P

In [155]:
data_currency

,Trades,Header,DataDiscriminator,Asset Category,Currency,Symbol,Date/Time,Quantity,T. Price,Unnamed: 9,Proceeds,Comm in USD,Unnamed: 12,Unnamed: 13,MTM in USD,Code
0,Trades,Data,Order,Forex,USD,AUD.USD,2021-03-23 09:43:37,1000000.0,0.76789,NaN,-7.678900e+05,-15.3578,NaN,NaN,-5330,NaN
1,Trades,Data,Order,Forex,USD,AUD.USD,2021-03-23 13:58:28,-1000000.0,0.76524,NaN,7.652400e+05,-15.3048,NaN,NaN,2680,NaN
2,Trades,Data,Order,Forex,JPY,EUR.JPY,2021-02-08 06:05:51,-500000.0,127.06,NaN,6.353000e+07,-12.05846066,NaN,NaN,1219.237,NaN
3,Trades,Data,Order,Forex,JPY,EUR.JPY,2021-02-08 11:03:11,500000.0,126.7,NaN,-6.335000e+07,-12.02429534,NaN,NaN,491.285,NaN
4,Trades,Data,Order,Forex,USD,EUR.USD,2021-01-07 05:14:10,20000.0,1.22683,NaN,-2.453660e+04,-2,NaN,NaN,1.4,NaN
5,Trades,Data,Order,Forex,USD,EUR.USD,2021-01-07 05:14:24,230000.0,1.2267,NaN,-2.821410e+05,-5.64282,NaN,NaN,46,NaN
6,Trades,Data,Order,Forex,USD,EUR.USD,2021-01-13 18:21:56,250000.0,1.21585,NaN,-3.039625e+05,-6.07925,NaN,NaN,-62.5,NaN
7,Trades,Data,Order,Forex,USD,EUR.USD,2021-02-01 07:44:10,500000.0,1.20858,NaN,-6.042900e+05,-12.0858,NaN,NaN,-1290,NaN
8,Trades,Data,Order,Forex,USD,EUR.USD,2021-02-22 10:13:29,-125000.0,1.21525,NaN,1.519062e+05,-3.038125,NaN,NaN,-68.75,NaN
9,Trades,Data,Order,Forex,USD,EUR.USD,2021-02-22 12:06:51,-125000.0,1.21576,NaN,1.519700e+05,-3.0394,NaN,NaN,-5,NaN
10,Trades,Data,Order,Forex,USD,EUR.USD,2021-02-22 12:24:21,-125000.0,1.21627,NaN,1.520338e+05,-3.040675,NaN,NaN,58.75,NaN
11,Trades,Data,Order,Forex,USD,EUR.USD,2021-02-22 14:42:16,-125000.0,1.21676,NaN,1.520950e+05,-3.0419,NaN,NaN,120,NaN
12,Trades,Data,Order,Forex,USD,EUR.USD,2021-02-22 19:52:39,-125000.0,1.21725,NaN,1.521562e+05,-3.043125,NaN,NaN,281.25,NaN
13,Trades,Data,Order,Forex,USD,EUR.USD,2021-02-23 02:48:43,-125000.0,1.21777,NaN,1.522212e+05,-3.044425,NaN,NaN,346.25,NaN
14,Trades,Data,Order,Forex,USD,EUR.USD,2021-02-23 10:20:05,125000.0,1.21485,NaN,-1.518562e+05,-3.037125,NaN,NaN,18.75,NaN
15,Trades,Data,Order,Forex,USD,EUR.USD,2021-02-23 11:33:22,-125000.0,1.21585,NaN,1.519812e+05,-3.039625,NaN,NaN,106.25,NaN
16,Trades,Data,Order,Forex,USD,EUR.USD,2021-02-25 00:13:38,-125000.0,1.21825,NaN,1.522812e+05,-3.045625,NaN,NaN,81.25,NaN
17,Trades,Data,Order,Forex,USD,EUR.USD,2021-02-25 02:59:00,-125000.0,1.21876,NaN,1.523450e+05,-3.0469,NaN,NaN,145,NaN
18,Trades,Data,Order,Forex,USD,EUR.USD,2021-03-08 17:16:45,125000.0,1.1849,NaN,-1.481125e+05,-2.96225,NaN,NaN,650,NaN
19,Trades,Data,Order,Forex,USD,EUR.USD,2021-03-09 04:10:15,-125000.0,1.18967,NaN,1.487088e+05,-2.974175,NaN,NaN,-53.75,NaN
20,Trades,Data,Order,Forex,USD,GBP.USD,2021-02-18 13:45:02,-300000.0,1.3971,NaN,4.191300e+05,-8.3826,NaN,NaN,-90,NaN
21,Trades,Data,Order,Forex,USD,GBP.USD,2021-02-19 07:55:51,300000.0,1.40132,NaN,-4.203960e+05,-8.40792,NaN,NaN,-66,NaN
22,Trades,Data,Order,Forex,USD,NZD.USD,2021-03-23 07:34:04,100000.0,0.70418,NaN,-7.041800e+04,-2,NaN,NaN,-431,NaN
23,Trades,Data,Order,Forex,USD,NZD.USD,2021-03-24 16:13:38,100000.0,0.69705,NaN,-6.970500e+04,-2,NaN,NaN,-201,NaN
24,Trades,Data,Order,Forex,USD,NZD.USD,2021-04-05 11:27:53,-200000.0,0.70682,NaN,1.413640e+05,-2.82728,NaN,NaN,140,NaN
25,Trades,Data,Order,Forex,CAD,USD.CAD,2021-02-18 16:30:50,-100000.0,1.26732,NaN,1.267320e+05,-2,NaN,NaN,-36.33304,NaN
26,Trades,Data,Order,Forex,CAD,USD.CAD,2021-02-19 07:15:45,100000.0,1.26289,NaN,-1.262890e+05,-2,NaN,NaN,-106.76452,NaN
27,Trades,Data,Order,Forex,JPY,USD.JPY,2021-01-21 07:50:21,323.0,103.395,NaN,-3.339658e+04,-2,NaN,NaN,0.315516,NaN
28,Trades,Data,Order,Forex,JPY,USD.JPY,2021-02-10 15:18:15,1722.0,104.655,NaN,-1.802159e+05,-2,NaN,NaN,-0.990251,NaN
29,Trades,Data,Order,Forex,JPY,USD.JPY,2021-03-03 14:52:14,1168.0,106.955,NaN,-1.249234e+05,-2,NaN,NaN,0.727869,NaN

In [156]:
def matching_trades(data):
    d = {}
    predict = pd.DataFrame(
        columns=['Symbol', 'opening_trades', 'close_trades', 'quantity', 'proceeds'])
    for i in data.index:
        symbol = data.Symbol[i]
        if symbol not in d:
            d[symbol] = {'symbol': symbol,
                         'time_start': data['Date/Time'][i],
                         'time_end': None,
                         'quantity': np.abs(data.Quantity[i])/2,
                         'proceeds': data.Proceeds[i]}
            count = data.Quantity[i]
        else:
            d[symbol]['time_end'] = data['Date/Time'][i]
            d[symbol]['quantity'] += np.abs(data.Quantity[i]/2)
            d[symbol]['proceeds'] += data.Proceeds[i]
            count += data.Quantity[i]
            
            if count == 0:
                predict = predict.append(pd.Series(d[symbol].values(), index=predict.columns), ignore_index=True)
                del d[symbol]
                
    return predict

In [157]:
matching_trades(data_currency)

    Symbol      opening_trades        close_trades   quantity   proceeds
0  AUD.USD 2021-03-23 09:43:37 2021-03-23 13:58:28  1000000.0   -2650.00
1  EUR.JPY 2021-02-08 06:05:51 2021-02-08 11:03:11   500000.0  180000.00
2  EUR.USD 2021-01-07 05:14:10 2021-02-25 02:59:00  1125000.0    2203.65
3  EUR.USD 2021-03-08 17:16:45 2021-03-09 04:10:15   125000.0     596.25
4  GBP.USD 2021-02-18 13:45:02 2021-02-19 07:55:51   300000.0   -1266.00
5  NZD.USD 2021-03-23 07:34:04 2021-04-05 11:27:53   200000.0    1241.00
6  USD.CAD 2021-02-18 16:30:50 2021-02-19 07:15:45   100000.0     443.00

In [158]:
matching_trades(data_bonds)

,Symbol,opening_trades,close_trades,quantity,proceeds
0,MUR 6 7/8 08/15/24,2021-02-04 15:45:37,2021-03-29 10:17:04,10000.0,150.0
1,SIG 4.7 06/15/24,2021-03-10 09:53:11,2021-04-06 13:03:22,50000.0,62.5